[package]
name = "traffic-analyzer-common"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["user"]
user = ["dep:aya"]

[dependencies]
aya = { workspace = true, optional = true }
bytemuck = { workspace = true, default-features = false }
